LW1
kerosen8/ml-course pull request #1
Opened 2024-09-26 21:22 UTC by kerosen8

2024-10-06 21:09 UTC, JanePlatonova reviewed
Опрацюйте зауваження

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +df = pd.read_csv('./data/OnlineNewsPopularityReduced.csv', delimiter=',')
мені довелось змінити шлях на абсолютний, щоб запрацювало

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +print(df.info())
Виведіть загальну інформацію про набір даних - це є . Яку кількість змінних він містить? Який тип змінних? Чи багато пропущених значень? - маєте написати.

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +print(df.describe())
не вдалий вибір виводу статистики, видно статистику лише по першій та останній ознаці, висновки зробити неможливо

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +plt.show()
Чи зробили якісь висновки по розподілу? можливо є викиди?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +plt.show()
висновки?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +
Що можна сказати про наявність помилкових значень? Чи багато нетипових значень?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +plt.show()
Чи пов'язані величини?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +imgs_correlation = df['num_imgs'].corr(df['shares'])
Чому саме такий коефіціент кореляції використовували?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +    print("images influence > videos influence")
вийшло, що вплив картинок більший. Але чи є він суттєвим?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +plt.show()
висновки?

2024-10-06 21:09 UTC, JanePlatonova commented on LW1/main.py
> +plt.show()
Висновки?
Замало аналізу на 4 бали

2024-10-06 23:04 UTC, kerosen8 commented on LW1/main.py
> +df = pd.read_csv('./data/OnlineNewsPopularityReduced.csv', delimiter=',')
df.info() виводить інформацію про кількість data columns і далі до кожної колонки відповідно: назву, кількість ненульових значень і її datatype.

![изображение](https://github.com/user-attachments/assets/d1048371-eaac-4ad1-ba27-8cbabaa8177a)
![изображение](https://github.com/user-attachments/assets/93bb265f-fcb8-48df-86b3-04eec6ce8505)

2024-10-06 23:06 UTC, kerosen8 commented on LW1/main.py
> +print(df.info())
df.info() виводить інформацію про кількість data columns і далі до кожної колонки відповідно: назву, кількість ненульових значень і її datatype.

![изображение](https://github.com/user-attachments/assets/b8e4fc53-4597-4054-a299-aa6a0d6f9d2f)
![изображение](https://github.com/user-attachments/assets/ecd0bea3-8797-4cec-a3dc-59ec10776d71)

2024-10-07 12:16 UTC, JanePlatonova commented on LW1/main.py
> +print(df.info())
тут скоріше про те, що побачивши результат виводу df.info(). ви маєте написати висновок, а ми побачити, що ви розумієте, що де дивитись

2024-10-08 18:32 UTC, hakuryuu96 requested changes
Було би гарно, щоби ви прикрепили до вашого пулреквесту в описі графіки і значення, що ви отримали і трохи їх протрактували. В коді досить важко читати пояснення, та і вони там не умісні. 
Здебільшого, під час роботи датасаєнтістом ви будете складати репорти по даних окремо, а не в коді. Непоганий час для потренуватися.

2024-10-08 18:32 UTC, hakuryuu96 commented on LW1/main.py
> +print("Кореляція між num_images і shares більша, ніж між num_images і shares, тобто зображення мають більший вплив на популярність статті, однак кореляція між кількістю зображень та shares достатньо
> Кореляція між num_images і shares більша, ніж між num_images і shares

Можливо тут малось на увазі щось інше))

2024-10-08 20:07 UTC, kerosen8 commented
Виправив помилку, додав description.

2024-10-22 16:07 UTC, onupmarchenko approved these changes

2024-10-22 16:13 UTC, merged